POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QudGVzdCIsImV4cCI6MTc0ODI5NDE2NSwidXNlcklkIjowfQ.5C7ivGWoyqtdha03LkF_xyvtPb7gAW7WPpUPcCIFpbw

{
    "name": "Test event 2",
    "description": "Another test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}